### ISSUE TITLE
accept dateutil.tz objects

### ISSUE THREAD

**Issue by alexhsamuel** [alexhsamuel/ora#13]
This is tricky because the `zoneinfo` API doesn't provide any mechanism for identifying time zones.

These time zone objects appear to have a `_filename` attribute, which we could use to load the same zoneinfo file.  But we'd have to have a Python time zone object that owns the underlying object,.

**Comment by pganssle** [comment]
@alexhsamuel I would not use the `zoneinfo` API as a general rule, and definitely don't rely on `_filename` for anything (it's not guaranteed to be populated).

That said, I'm not sure exactly what you need to be able to accept `dateutil` zones - if `ora` datetimes implement the `datetime.datetime` interface and `dateutil.tz` objects implement the `datetime.tzinfo` interface, it should already work (though it would obviously be *much* slower than what you've got).

If all you need is the IANA zone name, I've raised dateutil/dateutil#642 to track the addition of a canonical way to get the zone name for a `dateutil.tz.tzfile` object. I think there's not much to be done about the other `dateutil.tz` implementations, though.

**Comment by alexhsamuel** [comment]
@pganssle, yeah, my intent is explicitly not to reimplement the existing APIs, but to experiment with new ones.  This was intended to be a best-effort attempt to convert other time zone objects, as an API convenience.  I'd be delighted if there were a more reliable way to identify other time zones, both geographic and fixed-offset.  Thanks for opening the issue.
